services:
  server:
    environment:
      DOTNET_TieredPGO: "1"
      DOTNET_gcServer: "1"
      FIX_DISABLE_FILE_LOG: "1"
    tmpfs:
      - /app/log:size=256m

  client:
    environment:
      FIX_CLIENT_INITIATOR_CONFIG: fix-client-initiator-docker.cfg
      SERVER_HTTP_BASE: http://server:8081
      DOTNET_TieredPGO: "1"
      DOTNET_gcServer: "1"
      FIX_DISABLE_FILE_LOG: "1"
    tmpfs:
      - /app/log:size=256m

  benchmark:
    profiles: ["benchmark"]
    build:
      context: .
      dockerfile: Oms.Benchmark/Dockerfile
    container_name: oms-benchmark
    depends_on:
      - client
    environment:
      BENCHMARK_CONFIG: benchmark-client-docker.cfg
      FIX_DISABLE_FILE_LOG: "1"
